export const IS_GAME_STARTED = "IS_GAME_STARTED";
export const ADD_USER_SCORE = "ADD_USER_SCORE";
export const RESET_USER_SCORE = "RESET_USER_SCORE";
export const IS_CHECKBOX_VALID = "IS_CHECKBOX_VALID";
