export const CHANGE_USER_SCORE = "CHANGE_USER_SCORE";
export const IS_GAME_STARTED = "IS_GAME_STARTED";
export const SHOW_QUESTIONS = "SHOW_QUESTIONS";
export const IS_CHECKBOX_VALID = "IS_CHECKBOX_VALID";
